default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>
  timeout: 5000

development:
  primary:
    # This is the connection information for your primary database
    database: <%= ENV['DB_NAME'] %>
    username: <%= ENV['DB_USERNAME'] %>
    password: <%= ENV['DB_PASSWORD'] %>
    adapter: postgresql
    port: 5432
  readyset:
    database: <%= ENV['DB_NAME'] %>
    username: <%= ENV['DB_USERNAME'] %>
    password: <%= ENV['DB_PASSWORD'] %>
    host: <%= ENV['DB_HOST'] %>
    adapter: readyset
    port: 5433

test:
  <<: *default
  database: <%= ENV['POSTGRES_TEST_DB'] %>
  readyset:
    <<: *default
    database: prepared_test
production:
  <<: *default
